import { test, expect } from '@playwright/test'

test('city selection rotates the globe and free input interrupts focus', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/?debug=true')
  const label = page.locator('.city-label:not(.hidden)').first()
  await expect(label).toBeVisible({ timeout: 6000 })
  const name = await label.textContent()
  await label.press('Enter')
  await expect(page.locator('#city-name')).toHaveText(name!)
  await expect(page.locator('#city-country')).toContainText('国家代码')
  await expect(page.locator('#city-coordinates')).toContainText('°')
  await expect(page.locator('body')).toHaveAttribute('data-focusing', 'true')
  await expect(page.locator('body')).toHaveAttribute('data-focusing', 'false', { timeout: 4000 })
  await page.screenshot({ path: 'artifacts/city-exploration-desktop.png' })
  const next = page.locator('.city-label:not(.hidden)').last()
  await next.click({ force: true })
  await page.mouse.move(640, 450)
  await expect(page.locator('body')).toHaveAttribute('data-focusing', 'false')
  await page.mouse.down(); await page.mouse.move(740, 480, { steps: 8 }); await page.mouse.up()
  await page.locator('#close-city').click()
  await expect(page.locator('#city-info')).toBeHidden()
  expect(errors).toEqual([])
})

test('mobile city panel clears controls, labels and debug; touch drag stays usable', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/?debug=true')
  const label = page.locator('.city-label:not(.hidden)').first()
  await expect(label).toBeVisible({ timeout: 6000 })
  await label.click({ force: true })
  const panel = await page.locator('#city-info').boundingBox()
  expect(panel).not.toBeNull()
  for (const selector of ['.view-controls', '.tracking', '.bottom-panel', '#debug-panel']) {
    const box = await page.locator(selector).boundingBox()
    if (!box || !panel) continue
    const overlap = panel.x < box.x + box.width && panel.x + panel.width > box.x && panel.y < box.y + box.height && panel.y + panel.height > box.y
    expect(overlap, `city info overlaps ${selector}`).toBe(false)
  }
  await page.screenshot({ path: 'artifacts/city-exploration-mobile-debug.png' })
  await page.locator('#close-city').click()
  const yaw = async () => Number((await page.locator('#debug-panel').textContent())?.match(/ROTATION\s+[-\d.]+, ([-\d.]+)/)?.[1])
  const before = await yaw()
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 180, y: 420 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 240, y: 450 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(yaw).toBeGreaterThan(before + .05)
  await cdp.detach()
  await expect(page.locator('body')).toHaveAttribute('data-focusing', 'false')
  expect(errors).toEqual([])
})

test('wheel and drag over city text still operate the globe', async ({ page }) => {
  await page.goto('/?debug=true')
  const label = page.locator('.city-label:not(.hidden)').first()
  await expect(label).toBeVisible({ timeout: 6000 })
  const box = await label.boundingBox()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2)
  const debug = page.locator('#debug-panel')
  const scale = async () => Number((await debug.textContent())?.match(/SCALE\s+([\d.]+)/)?.[1])
  const yaw = async () => Number((await debug.textContent())?.match(/ROTATION\s+[-\d.]+, ([-\d.]+)/)?.[1])
  const before = await yaw()
  await page.mouse.down(); await page.mouse.move(box!.x + 100, box!.y + 20, { steps: 8 }); await page.mouse.up()
  await expect.poll(yaw).toBeGreaterThan(before + .05)
  await page.mouse.wheel(0, -10000)
  await expect.poll(scale).toBeGreaterThan(2.19)
  await page.screenshot({ path: 'artifacts/exploration-zoom-max.png' })
  const visible = page.locator('.city-label:not(.hidden)').first()
  const zoomedBox = await visible.boundingBox()
  if (zoomedBox) await page.mouse.move(zoomedBox.x + zoomedBox.width / 2, zoomedBox.y + zoomedBox.height / 2)
  await page.mouse.wheel(0, 20000)
  await expect.poll(scale).toBeLessThan(.66)
  await page.screenshot({ path: 'artifacts/exploration-zoom-min.png' })
})
