import { test, expect } from '@playwright/test'

test('immersive controls hide, reveal and exit; fullscreen failure is harmless', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/?debug=true')
  await page.locator('#toggle-immersive').click()
  await expect(page.locator('body')).toHaveClass(/immersive/)
  await page.mouse.move(640, 350)
  await expect(page.locator('body')).toHaveClass(/controls-hidden/, { timeout: 6000 })
  await expect(page.locator('#toggle-effect')).toBeHidden()
  await page.screenshot({ path: 'artifacts/immersive-desktop.png' })
  await page.mouse.move(650, 350)
  await expect(page.locator('#toggle-effect')).toBeVisible()
  await page.locator('#toggle-fullscreen').click()
  await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(true)
  await page.locator('#toggle-fullscreen').click()
  await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(false)
  await page.evaluate(() => { document.documentElement.requestFullscreen = () => Promise.reject(new Error('unsupported')) })
  await page.locator('#toggle-fullscreen').click()
  await expect(page.locator('#error-banner')).toContainText('仍可使用沉浸模式')
  await page.locator('#toggle-immersive').click()
  await expect(page.locator('body')).not.toHaveClass(/immersive/)
  expect(errors).toEqual([])
})

test('mobile immersion is revealed by a tap without blocking exit', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.locator('#toggle-immersive').click()
  await page.mouse.move(190, 350)
  await expect(page.locator('body')).toHaveClass(/controls-hidden/, { timeout: 6000 })
  await page.screenshot({ path: 'artifacts/immersive-mobile.png' })
  await page.locator('canvas.webgl').click({ position: { x: 50, y: 200 } })
  await expect(page.locator('#toggle-effect')).toBeVisible()
  await page.locator('#toggle-immersive').click()
  await expect(page.locator('body')).not.toHaveClass(/immersive/)
})

test('idle tour pauses on interaction and respects reduced motion', async ({ page }) => {
  await page.goto('/?debug=true')
  await expect(page.locator('body')).toHaveAttribute('data-cruising', 'true', { timeout: 22000 })
  const debug = page.locator('#debug-panel')
  const yaw = async () => Number((await debug.textContent())?.match(/ROTATION\s+[-\d.]+, ([-\d.]+)/)?.[1])
  const before = await yaw()
  await expect.poll(yaw).toBeGreaterThan(before + .015)
  await page.mouse.move(620, 350)
  await expect(page.locator('body')).toHaveAttribute('data-cruising', 'false')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.waitForTimeout(16000)
  await expect(page.locator('body')).toHaveAttribute('data-cruising', 'false')
})
